jwt:
  secretKey: secretKeytestauthorizationjwtmanagetokensecretKeytestauthorizationjwtmanagetokensecretKeytestauthorizationjwtmanagetokensecretKeytestauthorizationjwtmanagetoken
  expirationInMs: 3600000

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    showSql: true
    database: mysql
    hibernate:
      ddl-auto: create

  # After Spring Boot 2.6 Swagger ant_apth_matcher to path_pattern_parser
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviego?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Qwerasdf12#$


logging:
  level:
    org:
      hibernate:
        type:
          descripter:
            sql: trace